site_name: Ayuskey

theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  logo: https://s3.akirin.xyz/assets/ayuskey.png
  favicon: https://s3.akirin.xyz/assets/ayuskey.png
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: white
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: light green
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

repo_url: https://github.com/TeamBlackCrystal/misskey
repo_name: Ayuskey

plugins:
  - search
  - git-revision-date-localized
  - git-authors

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TeamBlackCrystal/misskey
  copyright: Copyright &copy; 2021-2022 TeamBlackCrystal



extra_css:
  - https://s3.akarinext.org/assets/*/custom.css
