site_name: Ayuskey

theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  logo: https://s3.akarinext.org/assets/*/ayuskey.png
repo_url: https://github.com/TeamBlackCrystal/misskey
repo_name: Ayuskey

plugins:
  - search
  - git-revision-date-localized
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TeamBlackCrystal/misskey
  copyright: Copyright &copy; 2021 TeamBlackCrystal

extra_css:
  - https://s3.akarinext.org/assets/*/custom.css